### ISSUE TITLE
Alignment in sales screen

### ISSUE THREAD

**Issue by AlienHu** [anupam42/PG-DAPP#58] opened 2016-07-25 06:38 UTC
Align ment of cart icon at the footer bar 
![image](https://cloud.githubusercontent.com/assets/13354052/17092452/6b488b76-5260-11e6-96ae-39b48302b35a.png)

**Comment by anupam42** [comment] 2016-08-01 15:37
The issue is already fixed :+1:  please do review and close the issue

**Comment by ParshuM** [comment] 2016-08-03 16:03
closed

**Closed as completed by ParshuM** 2016-08-03 16:03 UTC
Labels: Retail
