### ISSUE TITLE
Place order

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-DAPP#111] opened 2016-07-30 13:10 UTC
in place order when we place the orders that place order button not working properly its taking long time ..

![issue](https://cloud.githubusercontent.com/assets/20521598/17270609/04e189d2-5684-11e6-95fd-7ab1fc249b84.png)

**Comment by saichaitanyaeruvaram** [comment] 2016-07-31 07:30
Duplicate of 92 (https://github.com/anupam42/PG-DAPP/issues/92)

**Closed as completed** 2016-07-31 07:30 UTC
Labels: Bug, Restaurant
